version: '3.3'

services:
  
  webinar-db:
    image: webinar-db:v2
    networks:
      - app-net

  message-queue:
    image: nats:nanoserver
    networks:
      - app-net

  elasticsearch:
    image: elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - app-net

  kibana:
    image: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app-net

  save-handler:
    image: webinar-save-handler:v2
    depends_on:
      - webinar-db
      - message-queue
    networks:
      - app-net

  index-handler:
    image: webinar-index-handler:v2
    depends_on:
      - elasticsearch
      - message-queue
    networks:
      - app-net

  web-app:
    image: webinar-app:v5
    depends_on:
      - webinar-db
      - message-queue
    networks:
      - app-net

  homepage:
    image: umbraco:v1
    networks:
      - app-net

  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - web-app
      - homepage
    networks:
      - app-net

  prometheus:
    image: prometheus
    ports:
      - "9090:9090"
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat