global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'web'
    static_configs:
      - targets: ['web-app:50505']
  - job_name: 'index-handler'
    static_configs:
      - targets: ['index-handler:50505']
  - job_name: 'save-handler'
    static_configs:
      - targets: ['save-handler:50505']