version: '3.3'

services:
  
  message-queue:
    image: nats:nanoserver
    networks:
      - app-net

  elasticsearch:
    image: sixeyed/psod-mta-elasticsearch:nanoserver
    networks:
      - app-net

  kibana:
    image: sixeyed/psod-mta-kibana:windowsservercore
    networks:
      - app-net

  save-handler:
    image: sixeyed/psod-mta-save-handler:v3
    networks:
      - app-net

  index-handler:
    image: sixeyed/psod-mta-index-handler:v2
    networks:
      - app-net

  web-app:
    image: sixeyed/psod-mta-app:v6
    networks:
      - app-net

  homepage:
    image: sixeyed/psod-mta-umbraco:v1
    networks:
      - app-net

  nginx:
    image: sixeyed/psod-mta-nginx:windowsservercore
    networks:
      - app-net

  prometheus:
    image: sixeyed/psod-mta-prometheus:nanoserver
    networks:
      - app-net      

  grafana:
    image: sixeyed/psod-mta-grafana:v1
    networks:
      - app-net

networks:
  app-net: