version: '3.3'

services:

  webinar-db:
    image: sixeyed/psod-mta-db:v2
    networks:
      - app-net
    ports:
      - "1433:1433"

  elasticsearch:
    environment:
      - ES_JAVA_OPTS=-Xms300m -Xmx300m

  kibana:
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  save-handler:
    depends_on:
      - webinar-db
      - message-queue

  index-handler:
    depends_on:
      - elasticsearch
      - message-queue

  web-app:
    depends_on:
      - webinar-db
      - message-queue

  nginx:
    ports:
      - "80:80"
    depends_on:
      - web-app
      - homepage

  grafana:
    ports:
      - "3000:3000"

networks:
  app-net:
    external:
      name: nat